### ISSUE TITLE
Add log rotation properties to edgebox-compose.yml (and framework recommendations)

### ISSUE THREAD

**Issue by paulotruta** [edgebox-iot/ws#11]
**This would also be recommended to add to EdgeApps, as well as the API repository.**

Make Docker automatically rotate the logs for you.  Lpg options can be passed to individual containers to override these defaults, allowing you to save more or fewer logs on individual containers. From docker run this looks like:

`docker run --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 ...`
or in a compose file:

```
version: '3.7'
services:
  app:
    image: ...
    logging:
      options:
        max-size: "10m"
        max-file: "3"
```
